window.SYLLABUS_DATA = {
  course: {
    code: "EC550",
    title: "Development Economics for Research Students II",
    subtitle: "The Economics of Sustainable Development",
    instructor: "Robin Burgess",
    academicYear: "2024-2025",
    overview: [
      "There is now a central tension between economic growth, which is critical to poverty reduction, and the externalities from that economic growth in the form of climate change. How we steer a path towards continued prosperity in developing countries depends critically on how we balance the need for growth with the externalities from growth.",
      "This is important for two main reasons. First, growth is most needed in the world's poorer nations. Second, populations in these same nations are the ones that are being most hit by environmental damages such as climate change, which emanate from growth. This part of the course is all about the economics of sustainable development.",
      "In three lectures, I will focus centrally on energy. This is because lack of energy is a major constraint on economic development; modern firms and modern jobs cannot arise without universal access to reliable energy. The second reason is that energy demand is increasing much more rapidly in developing countries, and so the bulk of future energy consumption will be in these countries. This means that we have no choice but to find ways of continuing economic growth whilst reducing the damages that emanate from that growth by making energy cleaner.",
      "My lectures will come in three parts. In the first part, I will be looking at energy for populations that are at the subsistence level. Much of my interest here will be in how to increase access to energy. This is critical for getting people out of poverty and into more productive jobs and firms. At this subsistence level, the major issue is that these are the very populations that are both being hardest hit by environmental damages, and so getting them out of occupations and firms which are very subject to these damages is urgent, with access to modern reliable energy being a critical part of this.",
      "In the second lecture, I look at the transformation that takes place as populations move into ever bigger firms and cities. As populations move out of subsistence type jobs into small firms, as they move into cities and towns, this is where diffusion of clean energy into these countries becomes a central issue. We will be looking at a number of papers that focus not only on how households choose between different forms of energy, but also what effects integrating renewables into electricity grids has on prices, and also at factors that hold up the diffusion of clean energy.",
      "Finally, in the last lecture on the frontier, we will be thinking about the process of innovation, which ultimately is making renewable energy ever cheaper. A major question concerns how one drives innovation in clean energy, and we will be looking at a number of papers that examine this problem, and also at how innovation is pushing clean energy through electricity systems in low and middle income countries.",
    ],
  },
  sections: [
    {
      id: "sustainable-energy-transition",
      title: "Sustainable Energy Transition",
      collapsedByDefault: true,
      subsections: [
        {
          id: "carbon-markets-and-emissions-trading",
          title: "Carbon Markets and Emissions Trading",
          papers: [
            {
              id: "clausing_colmer_hsiao_wolfram_2025",
              title: "The Global Effects of Carbon Border Adjustment Mechanisms",
              authors: [
                "Kimberly A. Clausing",
                "Jonathan M. Colmer",
                "Allan Hsiao",
                "Catherine Wolfram",
              ],
              year: 2025,
              venue: "NBER Working Paper 33723",
              doi: "10.3386/w33723",
              core: false,
              localPdf:
                "papers/Clausing et al 2025 - The Global Effects of Carbon Border Adjustment Mechanisms.pdf",
              abstract:
                "Climate change poses a collective action problem: individual countries bear the costs of carbon regulation, while the benefits are shared globally. Carbon border adjustment mechanisms (CBAMs), which are currently being implemented by the EU and UK, aim to realign incentives by improving domestic competitiveness, reducing emissions leakage, and encouraging other countries to tax carbon. However, policy discussions also note that CBAMs could unfairly disadvantage lower-income trading partners. We evaluate these issues with a quantitative trade model and plant-level data for two key industries - steel and aluminum - which are the focus of early CBAM implementation. Together, they account for 14% of global emissions. We show that CBAMs can facilitate collective climate action, while largely avoiding disproportionate burdens on lower-income countries.",
              abstractStatus: "zotero",
            },
            {
              id: "greenstone_pande_ryan_sudarshan_2025",
              title:
                "Can Pollution Markets Work in Developing Countries? Experimental Evidence from India",
              authors: [
                "Michael Greenstone",
                "Rohini Pande",
                "Nicholas Ryan",
                "Anant Sudarshan",
              ],
              year: 2025,
              venue: "Quarterly Journal of Economics",
              doi: "10.1093/qje/qjaf009",
              core: false,
              localPdf:
                "papers/Greenstone et al 2025 - Can Pollution Markets Work in Developing Countries.pdf",
              abstract:
                "Market-based environmental regulations are seldom used in low-income countries, where pollution is highest but state capacity is often low. We collaborated with the Gujarat Pollution Control Board (GPCB) to design and experimentally evaluate the world's first particulate-matter emissions market, which covered industrial plants in a large Indian city. There are three main findings. First, the market functioned well. Treatment plants, randomly assigned to the emissions market, traded permits to become significant net sellers or buyers. After trading, treatment plants held enough permits to cover their emissions 99% of the time, compared with just 66% compliance with standards under the command-and-control status quo. Second, treatment plants reduced pollution emissions, relative to control plants, by 20%-30%. Third, the market reduced abatement costs by an estimated 11%, holding constant emissions. This cost-savings estimate is based on plant-specific marginal cost curves that we estimate from the universe of bids to buy and sell permits in the market. The combination of pollution reductions and low costs imply that the emissions market has mortality benefits that exceed its costs by at least 25 times. JEL codes: O13, Q56, L51.",
              abstractStatus: "zotero",
            },
          ],
        },
      ],
    },
    {
      id: "subsistence",
      title: "Subsistence",
      papers: [
        {
          id: "burlig_preonas_2024",
          title:
            "Out of the Darkness and into the Light? Development Effects of Rural Electrification",
          authors: ["Fiona Burlig", "Louis Preonas"],
          year: 2024,
          venue: "Journal of Political Economy",
          doi: "10.1086/730204",
          core: true,
          localPdf: "papers/Burlig & Preonas 2024 - Out of the Darkness.pdf",
          abstract: "Nearly 1 billion people still lack electricity access. Developing countries are investing billions of dollars in “last-mile” electrification, although evidence on its economic impacts is mixed. We estimate the development effects of rural electrification in the context of India’s national electrification program, RGGVY (Rajiv Gandhi Grameen Vidyutikaran Yojana), which reached over 400,000 villages. Using regression-discontinuity and difference-in-differences designs, we estimate that RGGVY meaningfully expanded electricity access. However, the program generated limited economic impacts after 3–5 years. Scaling our intent-to-treat estimates using instrumental variables, we find that “full electrification” reduces welfare in small villages but has a 33% internal rate of return in large villages.",
          abstractStatus: "zotero",
        },
        {
          id: "cisse_2025",
          title:
            "The Value of Electricity Reliability: Evidence from a Natural Experiment in Senegal",
          authors: ["Abdoulaye Cisse"],
          year: 2025,
          venue: "Working paper",
          url: "https://escholarship.org/uc/item/37h2h4ks",
          core: false,
          localPdf: "papers/Cisse 2025 - The Value of Electricity Reliability.pdf",
          abstract: "Governments and donors invest heavily in expanding access to electricity in low-income countries. However, recent studies document small impacts of access to grid electricity in several low-income countries. This paper provides new evidence on the impact of grid reliability on the willingness to pay (WTP) for grid electricity based on large-scale reliability improvement projects in Senegal's electricity supply network. I use high-frequency geocoded administrative data on outages, customer-level bills covering the universe of electricity users, and rich geocoded data on the economic activities of households and firms to conduct two analyses. First, I estimate the causal effect of improved reliability on consumers through a difference-in-differences that leverages the variation in the timing of reliability projects. Second, I estimate a quantitative demand model and a random-coefficient discrete choice model of energy sources. I find that reliability projects increase the WTP for an additional hour of grid electricity by 10%, from an average of $0.20. This increase varies over peak and off-peak hours and differs significantly across customer types (firms versus households) and by establishment size (small versus large). This finding corresponds to an internal rate of return for reliability projects exceeding 30%. My findings suggest that reliability improvements can significantly increase the value of grid electricity, even in contexts where baseline reliability and the WTP for grid electricity are low.",
          abstractStatus: "zotero",
        },
        {
          id: "dinkelman_2011",
          title:
            "The Effects of Rural Electrification on Employment: New Evidence from South Africa",
          authors: ["Taryn Dinkelman"],
          year: 2011,
          venue: "American Economic Review",
          doi: "10.1257/aer.101.7.3078",
          core: true,
          localPdf:
            "papers/Dinkelman 2011 - The Effects of Rural Electrification on Employment.pdf",
          abstract: "This paper estimates the impact of electrification on employment growth by analyzing South Africa's mass roll-out of electricity to rural households. Using several new data sources and two different identification strategies (an instrumental variables strategy and a fixed effects approach), I find that electrification significantly raises female employment within five years. This new infrastructure appears to increase hours of work for men and women, while reducing female wages and increasing male earnings. Several pieces of evidence suggest that household electrification raises employment by releasing women from home production and enabling microenterprises. Migration behavior may also be affected. (JEL H54, L94, L98, O15, O18, R23)",
          abstractStatus: "zotero",
        },
        {
          id: "fried_lagakos_2021",
          title:
            "Rural Electrification, Migration and Structural Transformation: Evidence from Ethiopia",
          authors: ["Stephie Fried", "David Lagakos"],
          year: 2021,
          venue: "Regional Science and Urban Economics",
          doi: "10.1016/j.regsciurbeco.2020.103625",
          core: false,
          localPdf: "papers/Fried & Lagakos 2021 - Rural Electrification, Migration and Structural Transformation.pdf",
          abstract: "To what extent does rural electrification induce structural change and alter migration patterns? This paper addresses this question using a simple multi-sector spatial model and evidence from a panel of rural Ethiopian villages during its recent expansion of electricity supply. We find that electrification raised irrigation rates, agricultural yields and non-agricultural business activity. Furthermore, electrified villages experienced higher rates of in-migration and lower rates of out-migration. Each of these predictions is qualitatively consistent with the predictions of our model. Our results suggest that rural electrification helped facilitate structural transformation of villages economies in Ethiopia and slowed out-migration from rural areas.",
          abstractStatus: "zotero",
        },
        {
          id: "greenstone_2024",
          title: "The Economics of the Global Energy Challenge",
          authors: ["Michael Greenstone"],
          year: 2024,
          venue: "AEA Papers and Proceedings",
          doi: "10.1257/pandp.20241000",
          core: true,
          localPdf: "papers/Greenstone 2024 - Global Energy Challenge.pdf",
          abstract: "Rather than facing an isolated climate change challenge, this paper argues that the\nworld must confront the Global Energy Challenge (GEC) that requires all countries\nto make trade-offs between three often competing and interrelated goals: inexpensive\nand reliable energy, clean air, and limiting damages from climate change. This paper\npresents seven facts that help illuminate the contours of the GEC and the interactions\nbetween the three goals. It concludes by outlining potential solutions: pricing energy at\nits full social cost, investing in technical and policy innovation, improving information\non pollution and climate damages, and treating energy as a private good.",
          abstractStatus: "zotero",
        },
        {
          id: "lee_miguel_wolfram_2020",
          title: "Experimental Evidence on the Economics of Rural Electrification",
          authors: ["Kenneth Lee", "Edward Miguel", "Catherine Wolfram"],
          year: 2020,
          venue: "Journal of Political Economy",
          doi: "10.1086/705417",
          core: true,
          localPdf:
            "papers/Lee et al 2020 - experimental evidence on the economics of rural electrification.pdf",
          abstract: "We present results from an experiment that randomized the expansion of electric grid infrastructure in rural Kenya. Electricity distribution is a canonical example of a natural monopoly. Experimental variation in the number of connections, combined with administrative cost data, reveals considerable scale economies, as hypothesized. Randomized price offers indicate that demand for connections falls sharply with price. Among newly connected households, average electricity consumption is very low, implying low consumer surplus. We do not find meaningful medium-run impacts on economic and noneconomic outcomes. We discuss implications for current efforts to increase rural electrification in Kenya and highlight how various factors may affect interpretation.",
          abstractStatus: "zotero",
        },
        {
          id: "lipscomb_mobarak_barham_2013",
          title:
            "Development Effects of Electrification: Evidence from the Topographic Placement of Hydropower Plants in Brazil",
          authors: ["Molly Lipscomb", "A. Mushfiq Mobarak", "Tania Barham"],
          year: 2013,
          venue: "American Economic Journal: Applied Economics",
          doi: "10.1257/app.5.2.200",
          core: false,
          localPdf: "papers/Lipscomb et al 2013 - Development Effects of Electrification.pdf",
          abstract: "We estimate the development effects of electrification across Brazil over the period 1960–2000. We simulate a time series of hypothetical electricity grids for Brazil for the period 1960–2000 that show how the grid would have evolved had infrastructure investments been made based solely on geography-based cost considerations. Using the model as an instrument, we document large positive effects of electrification on development that are underestimated when one fails to account for endogenous targeting. Broad-based improvement in labor productivity across sectors and regions rather than general equilibrium re-sorting appears to be the likely mechanism by which these development gains are realized. (JEL H54, L94, O11, O13, Q41, Q43)",
          abstractStatus: "zotero",
        },
        {
          id: "mcrae_2015",
          title: "Infrastructure Quality and the Subsidy Trap",
          authors: ["Shaun McRae"],
          year: 2015,
          venue: "American Economic Review",
          url: "https://www.jstor.org/stable/43497053",
          core: false,
          localPdf: "papers/McRae 2015 - Infrastructure Quality and the Subsidy Trap.pdf",
          abstract: "Electricity and water are often subsidized in developing countries to increase their affordability for low-income households. Ideally, such subsidies would create sufficient demand in poor neighborhoods to encourage private investment in their infrastructure. Instead, many regions receiving large subsidies have precarious distribution networks supplying users who never pay. Using a structural model of household electricity demand in Colombia, I predict the change in consumption and profits from upgrading low-quality electricity connections. I show that the existing subsidies, which provide greater transfers to areas with unreliable supply, deter investment to modernize infrastructure. Finally, I analyze alternative programs with stronger investment incentives.",
          abstractStatus: "zotero",
        },
        {
          id: "rud_2012",
          title: "Electricity Provision and Industrial Development: Evidence from India",
          authors: ["Juan Pablo Rud"],
          year: 2012,
          venue: "Journal of Development Economics",
          doi: "10.1016/j.jdeveco.2011.06.010",
          core: false,
          localPdf: "papers/Rud 2012 - Electricity Provision and Industrial Development.pdf",
          abstract: "I investigate the effect of electricity provision on industrialization using a panel of Indian states for 1965-1984. To address the endogeneity of investment in electrification, I use the introduction of a new agricultural technology intensive in irrigation (the Green Revolution) as a natural experiment. As electric pumpsets are used to provide farmers with cheap irrigation water, I use the uneven availability of groundwater at the start of the Green Revolution to predict divergence in the expansion of the electricity network and, ultimately, to quantify the effect of electrification on industrial outcomes. I present a series of tests to show that the electrification channel remains the most important one among alternative explanations that could link groundwater availability to industrialization directly or indirectly. Results show that an increase in one standard deviation in the measure of electrification is associated with an increase of around 14% in manufacturing output for a state at the mean of the distribution.",
          abstractStatus: "zotero",
        },
      ],
    },
    {
      id: "transformation",
      title: "Transformation",
      papers: [
        {
          id: "allcott_collardwexler_oconnell_2016",
          title: "How Do Electricity Shortages Affect Industry? Evidence from India",
          authors: ["Hunt Allcott", "Allan Collard-Wexler", "Stephen D. O'Connell"],
          year: 2016,
          venue: "American Economic Review",
          doi: "10.1257/aer.20140389",
          core: false,
          localPdf: "papers/Allcott et al 2016 - How Do Electricity Shortages Affect Industry.pdf",
          abstract: "We estimate the effects of electricity shortages on Indian manufacturers, instrumenting with supply shifts from hydroelectric power availability. We estimate that India's average reported level of shortages reduces the average plant's revenues and producer surplus by 5 to 10 percent, but average productivity losses are significantly smaller because most inputs can be stored during outages. Shortages distort the plant size distribution, as there are significant economies of scale in generator costs and shortages more severely affect plants without generators. Simulations show that offering interruptible retail electricity contracts could substantially reduce the impacts of shortages. (JEL D24, L60, L94, O13, O14, Q41)",
          abstractStatus: "zotero",
        },
        {
          id: "burgess_greenstone_ryan_sudarshan_2023",
          title: "Demand for Electricity on the Global Electrification Frontier",
          authors: ["Robin Burgess", "Michael Greenstone", "Nicholas Ryan", "Anant Sudarshan"],
          year: 2023,
          venue: "Working paper",
          url: "https://wrap.warwick.ac.uk/152572",
          core: true,
          localPdf:
            "papers/Burgess et al 2025 - The Global Electrification Frontier and Climate Change.pdf",
          abstract: "Off-grid solar promises a low-cost and carbon-free path to electrification. But do poor households want it? We run a multi-year pricing experiment in rural India to estimate demand over all electricity sources, including off-grid solar, diesel generators and the grid. We find that off-grid solar is an important stop-gap, but households value grid electrification 6.6 times more. The grid, however, barely increases global surplus, because grid marginal carbon damages nearly offset households' gains. We apply our model to data from Africa and find a similarly strong preference for the grid among households there, underscoring the external validity of our results.",
          abstractStatus: "zotero",
        },
        {
          id: "chakravorty_pelli_ural_marchand_2014",
          title: "Does the Quality of Electricity Matter? Evidence from Rural India",
          authors: ["Ujjayant Chakravorty", "Martino Pelli", "Beyza Ural Marchand"],
          year: 2014,
          venue: "Journal of Economic Behavior and Organization",
          doi: "10.1016/j.jebo.2014.04.011",
          core: false,
          localPdf: "papers/Chakravorty et al 2014 - Does the Quality of Electricity Matter.pdf",
          abstract: "This paper estimates the returns to household income due to improved access to electricity in rural India. We examine the effect of connecting a household to the grid and of the quality of electricity, defined as hours of daily supply. The analysis is based on two rounds of a representative panel of more than 10,000 households. We use the district-level density of transmission cables as instrument for the electrification status of the household. We find that a grid connection increases non-agricultural incomes of rural households by about 9% during the study period (1994–2005). However, a grid connection and a higher quality of electricity (in terms of fewer outages and more hours per day) increases non-agricultural incomes by about 28.6% in the same period.",
          abstractStatus: "zotero",
        },
        {
          id: "jack_smith_2020",
          title: "Charging Ahead: Prepaid Metering, Electricity Use, and Utility Revenue",
          authors: ["Kelsey Jack", "Grant Smith"],
          year: 2020,
          venue: "American Economic Journal: Applied Economics",
          doi: "10.1257/app.20180155",
          core: true,
          localPdf: "papers/Jack & Smith  2020 - Charging ahead.pdf",
          abstract: "Monthly bills for services such as electricity often go unpaid in developing countries. Prepaid meters offer a potential technological solution. In Cape Town, South Africa, over 4,000 residential customers on monthly billing were switched to prepaid metering, with random variation in the timing of the switch. In response, electricity use falls by 14 percent, driven at least in part by an increase in marginal price sensitivity. The decrease in revenue to the municipal electric utility is more than offset by lower revenue recovery costs. Switching poorer and more in-debt customers generates the greatest net revenue gains to the utility.",
          abstractStatus: "zotero",
        },
        {
          id: "kassem_2024",
          title:
            "Does Electrification Cause Industrial Development? Grid Expansion and Firm Turnover in Indonesia",
          authors: ["Dana Kassem"],
          year: 2024,
          venue: "Journal of Development Economics",
          doi: "10.1016/j.jdeveco.2023.103234",
          core: false,
          localPdf: "papers/Kassem 2024 - Does Electrification Cause Industrial Development.pdf",
          abstract: "I ask whether electrification causes industrial development. I combine newly digitized data from the Indonesian state electricity company with rich manufacturing census data. To understand how electrification can cause industrial development, I shed light on an important economic mechanism — firm turnover. In particular, I study the effect of the extensive margin of electrification (grid expansion) on the extensive margin of industrial development (firm entry and exit). To deal with endogenous grid placement, I use an instrumental variable approach exploiting the location of colonial electric infrastructure and the need for an interconnected grid on the island of Java. I find that electrification causes industrial development by increasing the number of manufacturing firms, manufacturing workers, and manufacturing output. Electrification increases firm entry rates, but also exit rates, and entry accounts for most of the increase in output. This is consistent with electrification lowering entry costs, increasing competition, and forcing unproductive firms to exit more often.",
          abstractStatus: "zotero",
        },
        {
          id: "moneke_2020",
          title: "Can Big Push Infrastructure Unlock Development? Evidence from Ethiopia",
          authors: ["Niclas Moneke"],
          year: 2020,
          venue: "Working paper",
          url: "https://niclasmoneke.com/research/",
          core: false,
          localPdf: "papers/Moneke 2020 - Can Big Push Infrastructure Unlock Development.pdf",
          abstract: "Roads are instrumental to market access. Electricity is a key technology for modern production. Both have been widely studied in isolation. In reality, infrastructure investments are commonly bundled. How such big push infrastructure investments interact in causing economic development, however, is not well understood. To this end, I first develop a spatial general equilibrium model to understand how big push infrastructure investments may differ from isolated investments. Second, I track the large-scale road and electricity network expansions in Ethiopia over the last two decades and present causal reduced-form evidence confirming markedly different patterns: access to an all-weather road alone increases services employment, at the expense of manufacturing. In contrast, additionally electrified locations see large reversals in the manufacturing employment shares. Third, I leverage the model to structurally estimate the implied welfare effects of big push infrastructure investments. I find welfare in Ethiopia increased by at least 11% compared to no investments, while isolated counterfactual road (electrification) investments would have increased welfare by only 2% (0.7%).",
          abstractStatus: "zotero",
        },
        {
          id: "ryan_2021b",
          title: "Holding Up Green Energy",
          authors: ["Nicholas Ryan"],
          year: 2021,
          venue: "NBER Working Paper 29154",
          doi: "10.3386/w29154",
          core: true,
          localPdf: "papers/Ryan 2021 - Holding up green energy.pdf",
          abstract: "Green energy is produced by relationship-specific assets that are vulnerable to hold-up if contracts are not strictly enforced. I study the role of counterparty risk in the procurement of green energy using data on the universe of solar procurement auctions in India. The Indian context allows clean estimates of how risk affects procurement, because solar power plants set up in the same states, by the same firms, are procured in auctions variously intermediated by either risky states themselves or the central government. I find that: (i) the counterparty risk of an average state increases solar energy prices by 10%; (ii) the intermediation of the central government eliminates this risk premium; (iii) higher prices due to risk reduce investment, because state demand for green energy is elastic. The results suggest that the risk of hold-up places developing countries at a disadvantage in the procurement of green energy.",
          abstractStatus: "zotero",
        },
        {
          id: "wolfram_shelef_gertler_2012",
          title: "How Will Energy Demand Develop in the Developing World?",
          authors: ["Catherine Wolfram", "Orie Shelef", "Paul Gertler"],
          year: 2012,
          venue: "Journal of Economic Perspectives",
          doi: "10.1257/jep.26.1.119",
          core: false,
          localPdf: "papers/Wolfram et al 2012 - How Will Energy Demand Develop in the Developing World.pdf",
          abstract: "Over the next 25 to 30 years, nearly all of the growth in energy demand, fossil fuel use, associated local pollution, and greenhouse gas emissions is forecast to come from the developing world. This paper argues that the world's poor and near-poor will play a major role in driving medium-run growth in energy consumption. As the world economy expands and poor households' incomes rise, they are likely to get connected to the electricity grid, gain access to good roads, and purchase energy-using assets like appliances and vehicles for the first time. We argue that the current forecasts for energy demand in the developing world may be understated because they do not accurately capture growth in demand along the extensive margin, as low-income households buy their first durable appliances and vehicles. Within a country, the adoption of energy-using assets typically follows an S-shaped pattern: among the very poor, we see little increase in the number of households owning refrigerators, vehicles, air conditioners, and other assets as incomes go up; above a first threshold income level, we see rapid increases of ownership with income; and above a second threshold, increases in ownership level off. A large share of the world's population has yet to go through the first transition, suggesting there is likely to be a large increase in the demand for energy in the coming years.",
          abstractStatus: "zotero",
        },
      ],
    },
    {
      id: "frontier",
      title: "Frontier",
      papers: [
        {
          id: "arkolakis_walsh_2023",
          title: "Clean Growth",
          authors: ["Costas Arkolakis", "Conor Walsh"],
          year: 2023,
          venue: "NBER Working Paper 31615",
          doi: "10.3386/w31615",
          core: true,
          localPdf: "papers/Arkolakis & Walsh 2023 - Clean growth.pdf",
          abstract: "We provide a spatial theory of clean growth to assess the global impact of the rise of renewable energy. We model the details of the combined production and transmission network of electricity (“the grid”) that determine the supply and losses of energy in space. The local rate of clean energy adoption depends on learning-by-doing, the global electricity and trade network, and regional comparative advantage in renewable resources. We use the model to measure the aggregate and spatial implications of clean growth. We find that the world’s power system is likely to be dominated by renewables by 2040 in a range of scenarios, with substantial welfare gains, even in the absence of policy. Incorporating policy, we find that the US Inflation Reduction Act significantly accelerates renewable uptake, and generates substantial economic benefits. In addition, planned grid improvements lower prices substantially in many areas of the US, justifying their cost of construction.",
          abstractStatus: "zotero",
        },
        {
          id: "banares_sanchez_burgess_laszlo_simpson_vanreenen_wang_2023",
          title: "Ray of Hope? China and the Rise of Solar Energy",
          authors: [
            "Ignacio Banares-Sanchez",
            "Robin Burgess",
            "David Laszlo",
            "Pol Simpson",
            "John Van Reenen",
            "Yifan Wang",
          ],
          year: 2023,
          venue: "Working paper",
          url: "https://ignaciobanares.com/solar.pdf",
          core: true,
          localPdf: "papers/Sanchez et al 2025 - Ray of hope.pdf",
          abstract: "Do industrial policies that promote clean energy offer a \"ray of hope\", increasing a country's growth and welfare, whilst simultaneously reducing carbon emissions? We study the impact of Chinese solar subsidies whose implementation by city-regions went alongside massive expansion of the sector and a dramatic fall in global solar prices. We construct new city and firm panel data on solar policies, patenting and output. Using synthetic-difference-in-differences 2004-2020, we find production and innovation subsidies were more effective than demand-side (installation) subsidies in generating large and persistent increases in local innovation, net entry, exports, output and inputs. Demand policies did, however, reduce local pollution. To examine aggregate effects, we build and structurally estimate a quantitative spatial model with endogenous innovation and heterogeneous productivity across firms and cities, which accounts for business stealing and knowledge spillovers. Counterfactual analysis shows that: (i) local effects remain substantial at the macro level explaining 40%-50% of the aggregate changes in solar innovation, prices and revenues; (ii) social benefits to Chinese citizens exceed subsidy costs by 65% (and double this when environmental benefits are included); and (iii) although all subsidy types increase welfare, innovation subsidies are the most cost-effective.",
          abstractStatus: "zotero",
        },
        {
          id: "besley_persson_2023",
          title: "The Political Economics of Green Transitions",
          authors: ["Timothy Besley", "Torsten Persson"],
          year: 2023,
          venue: "Quarterly Journal of Economics",
          doi: "10.1093/qje/qjad006",
          core: false,
          localPdf: "papers/Besley & Persson 2023 - The Political Economics of Green Transitions.pdf",
          abstract: "Reducing the emissions of greenhouse gases may be almost impossible without a green transition—a substantial transformation of consumption and production patterns. To study such transitions, we propose a dynamic model, which differs from the common approach in economics in two ways. First, consumption patterns reflect not just changing prices and taxes, but changing values. Transitions of values and technologies create a dynamic complementarity that can help or hinder a green transition. Second, and unlike fictitious social planners, policy makers in democratic societies cannot commit to future policy paths, as they are subject to regular elections. We show that market failures and government failures can interact to prevent a welfare-increasing green transition from materializing or make an ongoing green transition too slow.",
          abstractStatus: "zotero",
        },
        {
          id: "gonzales_ito_reguant_2023",
          title:
            "The Investment Effects of Market Integration: Evidence From Renewable Energy Expansion in Chile",
          authors: ["Luis E. Gonzales", "Koichiro Ito", "Mar Reguant"],
          year: 2023,
          venue: "Econometrica",
          doi: "10.3982/ECTA20769",
          core: true,
          localPdf:
            "papers/Gonzales et al 2023 - The Investment Effects of Market Integration - Evidence From Renewable Energy Expansion in Chile.pdf",
          abstract: "We study the investment effects of market integration on renewable energy expansion. Our theory highlights that market integration not only improves allocative efficiency by gains from trade but also incentivizes new investment in renewable power plants. To test our theoretical predictions, we examine how recent grid expansions in the Chilean electricity market changed electricity production, wholesale prices, generation costs, and renewable investments. We then build a structural model of power plant entry to quantify the impact of market integration with and without the investment effects. We find that the market integration in Chile increased solar generation by around 180%, saved generation costs by 8%, and reduced carbon emissions by 5%. A substantial amount of renewable entry would not have occurred in the absence of market integration. Our findings suggest that ignoring these investment effects would substantially understate the benefits of market integration and its important role in expanding renewable energy.",
          abstractStatus: "zotero",
        },
        {
          id: "kellogg_reguant_2021",
          title:
            "Energy and Environmental Markets, Industrial Organization, and Regulation",
          authors: ["Ryan Kellogg", "Mar Reguant"],
          year: 2021,
          venue: "Handbook of Industrial Organization",
          doi: "10.1016/bs.hesind.2021.11.017",
          core: false,
          localPdf: "papers/Kellogg & Reguant 2021 - Energy and Environmental Markets, Industrial Organization, and Regulation.pdf",
          abstract: "This chapter discusses contributions that industrial organization economists have made to our understanding of energy markets and environmental regulation. We emphasize the substantive contributions of recent papers while also highlighting how this literature has adopted and sometimes augmented theoretical and empirical tools from industrial organization. Many of the topics examined by this literature—especially auctions, investment, productivity and innovation, and regulation—also apply to a variety of settings beyond energy and the environment. We also indicate areas where future research is likely to be fruitful, with an emphasis on how industrial organization economists can help inform energy and environmental policies.",
          abstractStatus: "zotero",
        },
        {
          id: "ryan_2021a",
          title:
            "The Competitive Effects of Transmission Infrastructure in the Indian Electricity Market",
          authors: ["Nicholas Ryan"],
          year: 2021,
          venue: "American Economic Journal: Microeconomics",
          doi: "10.1257/mic.20180191",
          core: false,
          localPdf: "papers/Ryan 2021 - The Competitive Effects of Transmission Infrastructure in the Indian Electricity Market.pdf",
          abstract: "The integration of markets may improve efficiency by lowering costs or reducing local market power. India, seeking to reduce electricity shortages, set up a new power market, in which transmission constraints sharply limit trade between regions. During congested hours, measures of market competitiveness fall and firms raise bid prices. I use confidential bidding data to estimate the costs of power supply and simulate market outcomes with more transmission capacity. Counterfactual simulations show that transmission expansion increases market surplus by 22 percent, enough to justify the investment. One-third of this gain is due to sellers’ response to a more integrated grid. (JEL H54, L13, L94, O13, Q41)",
          abstractStatus: "zotero",
        },
        {
          id: "ryan_2020",
          title:
            "Contract Enforcement and Productive Efficiency: Evidence From the Bidding and Renegotiation of Power Contracts in India",
          authors: ["Nicholas Ryan"],
          year: 2020,
          venue: "Econometrica",
          doi: "10.3982/ECTA17041",
          core: false,
          localPdf: "papers/Ryan 2020 - Contract Enforcement and Productive Efficiency.pdf",
          abstract: "Weak contract enforcement may reduce the efficiency of production in developing countries. I study how contract enforcement affects efficiency in procurement auctions for the largest power projects in India. I gather data on bidding and ex post contract renegotiation and find that the renegotiation of contracts in response to cost shocks is widespread, despite that bidders are allowed to index their bids to future costs like the price of coal. To study heterogeneity in bidding strategies, I construct a new measure of firm connectedness, based on whether a firm has been awarded coal concessions by the Government. Connected firms choose to index less of the value of their bids to coal prices and, through this strategy, expose themselves to cost shocks to induce renegotiation. I use a structural model of bidding in a scoring auction to characterize equilibrium bidding when bidders are heterogeneous both in cost and in the payments they expect after renegotiation. The model estimates show that bidders offer power\n              below\n              cost due to the expected value of later renegotiation. The model is used to simulate bidding and efficiency with strict contract enforcement. Contract enforcement is found to be pro‐competitive. With no renegotiation, equilibrium bids would rise to cover cost, but markups relative to total contract value fall sharply. Production costs decline, due to projects being allocated to lower‐cost bidders over those who expect larger payments in renegotiation.",
          abstractStatus: "zotero",
        },
      ],
    },
  ],
};
